import PORTRAIT_ASCII from "./portrait.txt?raw";

export const SITE = {
  name: "Dan He",
  role: "Founding Designer",
  company: "Virtue AI",
  location: "San Francisco",
  status: "Open to work",
  email: "dhe052@hotmail.com",
  linkedin: "#",
  heroTitleA: "I design AI products",
  heroTitleB: "and ship them to production.",
  heroBlurb: "Founding designer at Virtue AI. Brand, product, systems, web.",
  artSignature: "Kernel — generative study",
};

export const NOT_FOUND = {
  code: "404",
  line: "This path doesn't exist — the art doesn't mind.",
  cta: "[ back to index ]",
};

export const KALEIDO = {
  width: 48,
  height: 20,
  ramp: " .:-=+*o#%@",
};

export const ART = {
  defaults: {
    variant: "fold",
    symmetry: 6,
    speed: 2,
    scale: 13,
    density: -5,
    palette: "signal",
    customColor: "#C8432A",
    customMode: "multi",
    seed: 0.37,
  },
  variants: [
    { id: "fold", label: "K-Fold" },
    { id: "wave", label: "Wave" },
    { id: "orbit", label: "Orbit" },
    { id: "grid", label: "Moiré" },
  ],
  palettes: [
    { id: "signal", label: "Signal", accent: "#C8432A", colors: { base: "#4a4643", mid: "#8a817a", high: "#C8432A", peak: "#e86a4f" } },
    { id: "ink", label: "Mono Ink", accent: "#F7F5F0", colors: { base: "#3c3934", mid: "#6e6a63", high: "#b5aea4", peak: "#F7F5F0" } },
    { id: "ember", label: "Ember", accent: "#ff6a3c", colors: { base: "#4a2018", mid: "#8a3524", high: "#C8432A", peak: "#ff8a5f" } },
    { id: "terminal", label: "Terminal", accent: "#4fae5f", colors: { base: "#1d3a24", mid: "#2f6b3d", high: "#4fae5f", peak: "#a8ff7a" } },
    { id: "glacier", label: "Glacier", accent: "#5ba3d0", colors: { base: "#22303c", mid: "#3d5a70", high: "#5ba3d0", peak: "#bfe6ff" } },
    { id: "spectrum", label: "Spectrum", accent: "#7a5fff", spectrum: true },
  ],
};

export const WORKS = [
  {
    id: "policyguard",
    motif: "rings",
    num: "01",
    title: "PolicyGuard",
    type: "Product",
    tagline: "The guardrail, rebuilt for the people who own the policy",
    sub: "Virtue's most profitable product was an API only ML engineers could use. I reframed it into a product a policy owner at a bank or hospital composes, tests, and ships on their own.",
    tags: ["0→1", "AI safety", "Enterprise", "2026"],
    result: "Reframed Virtue's most profitable API into a product non-engineers ship on their own. Live as the flagship since Jan 2026.",
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "The most profitable product was an API only ML engineers could use.",
        body: "When I joined, Virtue was a handful of people, one product owner per product, two products: Guard and red teaming. Guard shipped as an API you tested against, and it quietly became our most profitable line. The demand was there. The form wasn't. A profitable product proves demand, not that it's in the right shape.",
        imgs: [
          { src: "/work/pg-dashboard-light.png", cap: "Dashboard, production scale" },
          { src: "/work/pg-dashboard-dark.png", cap: "Same dashboard, dark theme" },
        ],
      },
      {
        id: "focus",
        label: "02 Focus",
        headline: "I bet the opportunity was who could use it, not what it could do.",
        body: "I could have kept hardening the API for the engineers who already loved it. I focused elsewhere. This was a genuinely powerful tool, and its power was trapped behind ML expertise. If a PM, a compliance lead, or a stakeholder on any team could wield it, each of them could create impact with it, and that reach is where the larger business value was, not another model feature. Widening who can hold a powerful tool beats deepening it for the few who already can.",
      },
      {
        id: "problem",
        label: "03 Problem & Opportunity",
        headline: "The person who owns the policy can't tune the model.",
        body: "Trust-and-safety leads at a bank think in rules and obligations. The ML team thinks in thresholds and eval sets. Our real buyers, healthcare and finance moving into AI with no ML team, needed our engineers to hand-hold every deployment. That friction wasn't a training gap. It was a product gap. Whoever let a non-engineer compose enforcement first would own the category.",
        imgs: [
          { src: "/work/pg-old-config.png", cap: "The before: checkboxes, a threshold slider, and a raw API call" },
        ],
      },
      {
        id: "build",
        label: "04 The Build",
        headline: "Compose a guard, not configure a model.",
        body: "Both audiences needed one shared conceptual model: rules roll up into policy groups, policy groups into a guard. A non-engineer assembles real enforcement by touching a single object, its complexity addressable but underneath. That's object-oriented UX. The objects and how they nest are the product, not a settings panel.\n\nThe call that shaped it wasn't mine alone. My instinct was one clean screen: author now, test later. The product owner pushed back. In an AI-native tool, assembly you can't test is meaningless, because you can't judge a policy without running it. He was right. So authoring and evaluation became one loop, the editor beside a live playground. The busier interface I paid down with progressive disclosure: the playground stays disabled until the object exists, so a first-timer meets one path, not a wall.",
        diagram: "composition",
        imgs: [
          { src: "/work/pg-policy-groups.png", cap: "Policy groups: Governance and Customization" },
          { src: "/work/pg-new-policy-menu.png", cap: "Create from scratch, PDF, JSON, or by agent" },
          { src: "/work/pg-editor-playground.png", cap: "Editor and playground, side by side" },
          { src: "/work/pg-editor-playground-error.png", cap: "Validation states" },
        ],
      },
      {
        id: "outcome",
        label: "05 Outcome",
        headline: "Virtue's flagship, in enterprise hands.",
        body: "PolicyGuard shipped January 2026 and is now the flagship, in continuous iteration since. It's used by enterprise customers across financial services, healthcare, and tech, and reaches from single-prompt checks to full multiturn agent sessions. It reset who a guardrail product is for.",
        imgs: [
          { src: "/work/pg-policy-lab-step1.png", cap: "Policy Lab: pick a dataset" },
          { src: "/work/pg-policy-lab-step2.png", cap: "Evaluate a guard against real queries" },
          { src: "/work/pg-policy-lab-optimization-history.png", cap: "Optimization runs" },
          { src: "/work/pg-policy-lab-optimization-detail.png", cap: "Measured gain, with a diff to review and promote" },
          { src: "/work/pg-queries.png", cap: "Monitoring: flagged queries" },
          { src: "/work/pg-queries-session-trace.png", cap: "Multiturn agent session trace" },
          { src: "/work/pg-queries-session-trace-2.png", cap: "Per-turn flags" },
        ],
      },
      {
        id: "contribution",
        label: "06 Contribution",
        headline: "What was mine: the abstraction, the component, the two-day loop.",
        body: "Founding design isn't touching every surface. It's setting the few things everything else inherits. Mine were the composition model the product is built on, the card component reused across policy groups, datasets, evaluations, and the query tables on the dashboard and monitoring views, and a way of working: prototyping in code alongside engineers, branching off the PO's branch and sharing two live links to pick a direction, which took Policy Lab from design to deployment in two days over three rounds.",
        imgs: [
          { src: "/work/pg-dashboard-query-table.png", cap: "The same query table component, reused on the dashboard" },
        ],
      },
      {
        id: "next",
        label: "07 Next",
        headline: "A system the next designer can extend without me.",
        body: "The real test of what I built is whether the next hire can extend it without me in the room, using the same abstraction, the same components, the same rules. That is what the design-system work is about.",
        link: { to: "design-system", label: "Open the design system" },
      },
    ],
  },
  {
    id: "virtuered",
    wip: true,
    motif: "clash",
    num: "02",
    title: "VirtueRed",
    type: "Product",
    tagline: "The AI red-teaming platform, refactored",
    sub: "Rebuilding an engineer-built adversarial testing tool into an interface security researchers can move fast in.",
    tags: ["Refactor", "AI safety", "Systems", "2025"],
    result: "[Dan fills: one-line win]",
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "An engineer-built tool with no design system.",
        body: "[Dan fills: what the tool was, who used it, and what state it was in when you picked it up.]",
        fig: "drop screenshot — the before state",
      },
      {
        id: "gap",
        label: "02 The Gap",
        headline: "[Dan fills: what you saw]",
        body: "[Dan fills: what prompted the refactor — where researchers were losing time or trust.]",
      },
      {
        id: "fix",
        label: "03 The Fix",
        headline: "[Dan fills: the key decision]",
        body: "[Dan fills: what you redesigned — IA, interaction patterns, visual system — and the one call you'd defend.]",
        fig: "drop screenshot — the after state",
      },
      {
        id: "shipped",
        label: "04 What Shipped",
        headline: "[Dan fills]",
        body: "[Dan fills: what went to production and the scope you owned.]",
      },
      {
        id: "outcome",
        label: "05 Outcome",
        headline: "[Dan fills]",
        body: "[Dan fills: impact and what changed.]",
      },
    ],
  },
  {
    id: "design-system",
    wip: true,
    motif: "lattice",
    num: "03",
    title: "Design System",
    type: "System",
    tagline: "One language across every product",
    sub: "Tokens, components, and rules that let one designer keep two AI products — and everything around them — coherent.",
    tags: ["Systems", "Tokens", "Components", "2025"],
    result: "[Dan fills: one-line win — e.g. Two products, one system, zero drift]",
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "Two products, one designer, no shared parts.",
        body: "[Dan fills: the state of the UI across PolicyGuard and VirtueRed before the system existed.]",
      },
      {
        id: "gap",
        label: "02 The Gap",
        headline: "Every screen was drifting from the last.",
        body: "[Dan fills: where inconsistency was costing speed and trust — eng rebuilding variants, mismatched patterns.]",
      },
      {
        id: "fix",
        label: "03 The Fix",
        headline: "Tokens first, components second, rules third.",
        body: "[Dan fills: how you structured the system — color/type/spacing tokens, core components, usage rules — and how AI tooling helped you ship it solo.]",
        fig: "drop screenshot — token + component sheet",
      },
      {
        id: "shipped",
        label: "04 What Shipped",
        headline: "[Dan fills]",
        body: "[Dan fills: coverage — which products and surfaces run on the system.]",
        fig: "drop screenshot — system in production",
      },
      {
        id: "outcome",
        label: "05 Outcome",
        headline: "[Dan fills]",
        body: "[Dan fills: build speed, consistency, eng adoption.]",
      },
    ],
  },
  {
    id: "branding",
    wip: true,
    motif: "mark",
    num: "04",
    title: "Branding",
    type: "Brand",
    tagline: "Identity for an AI-safety company",
    sub: "The visual voice of Virtue AI — credible to enterprises, sharp enough for researchers.",
    tags: ["Identity", "Voice", "Collateral", "2025"],
    result: "[Dan fills: one-line win]",
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "A research-grade company that looked like a preprint.",
        body: "[Dan fills: what the brand was before — and who it needed to convince: buyers, researchers, candidates.]",
      },
      {
        id: "gap",
        label: "02 The Gap",
        headline: "[Dan fills: the positioning problem]",
        body: "[Dan fills: what the old identity failed to communicate.]",
      },
      {
        id: "fix",
        label: "03 The Fix",
        headline: "[Dan fills: the identity system]",
        body: "[Dan fills: logo, type, color, and the rules — how safety + credibility read visually.]",
        fig: "drop image — identity board",
      },
      {
        id: "shipped",
        label: "04 What Shipped",
        headline: "[Dan fills]",
        body: "[Dan fills: decks, social, events, collateral — everywhere the brand runs.]",
        fig: "drop image — brand in the wild",
      },
      {
        id: "outcome",
        label: "05 Outcome",
        headline: "[Dan fills]",
        body: "[Dan fills: what changed — perception, pipeline, recognition.]",
      },
    ],
  },
  {
    id: "website",
    wip: true,
    motif: "flow",
    num: "05",
    title: "Website",
    type: "Web",
    tagline: "virtueai.com — story, system, ship",
    sub: "The marketing site: explaining hard AI-safety products clearly, designed and shipped hands-on.",
    tags: ["Web", "Marketing", "Copy", "2025"],
    result: "[Dan fills: one-line win]",
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "Complex products, one page to earn trust.",
        body: "[Dan fills: what the site needed to do — for buyers, researchers, candidates.]",
      },
      {
        id: "gap",
        label: "02 The Gap",
        headline: "[Dan fills: what wasn't landing]",
        body: "[Dan fills: where the old site lost people — story, IA, clarity.]",
      },
      {
        id: "fix",
        label: "03 The Fix",
        headline: "[Dan fills: IA + narrative + build]",
        body: "[Dan fills: how you restructured the story, wrote the copy, and worked in the codebase to ship it.]",
        fig: "drop screenshot — homepage",
      },
      {
        id: "shipped",
        label: "04 What Shipped",
        headline: "[Dan fills]",
        body: "[Dan fills: pages, launches, product pages shipped.]",
        fig: "drop screenshot — product page",
      },
      {
        id: "outcome",
        label: "05 Outcome",
        headline: "[Dan fills]",
        body: "[Dan fills: traffic, conversion, feedback.]",
      },
    ],
  },
];

export const ABOUT = {
  id: "about",
  num: "06",
  title: "Dan He",
  type: "Profile",
  tagline: "Founding designer, generalist by necessity",
  sub: "San Francisco Bay Area. Currently the founding designer at Virtue AI.",
  tags: ["She/her", "SF Bay Area", "Open to work"],
  photo: "",
  portraitAscii: PORTRAIT_ASCII,
  result: null,
  sections: [
    {
      id: "bio",
      label: "01 Bio",
      headline: "One designer, every surface.",
      body: "Founding designer at Virtue AI, an AI security company. The role spans product design across PolicyGuard and VirtueRed, plus the design system, brand, and website. Not a strong coder, but close enough to the code to work in it: shipping styling, copy, and interaction details alongside engineers, using AI to close the gap between design intent and what actually ships.",
    },
    {
      id: "experience",
      label: "02 Experience",
      headline: "Founding designer, by way of brand and product.",
      body: "Founding Designer · Virtue AI\nApr 2025 – Present\nFounding and sole designer at an AI security company, owning product, brand, and web for tools used daily by AI engineers and security teams. Led UX for guardrail, red teaming, and policy configuration, translating complex technical workflows into clear interaction models. Designed PolicyGuard 0→1 from research to launch, refactored the Red Teaming product with engineering, built the company's first design system and brand from scratch, and shipped design directly in the front-end codebase alongside engineers.\n\nDesign Lead · YLEM LLC\nFeb 2024 – Apr 2025\nLed visual and product design across digital experiences and brand execution. Collaborated with clients to define design direction and deliver cohesive user-facing experiences.\n\nUX/UI Design Intern · Mindray\nNov 2022 – Jan 2023\nDesigned ultrasound workstation UX for region-of-interest (ROI) editing and image reordering workflows used in cardiac measurement.\n\nBrand Designer · Zhide Health Consulting\nApr 2019 – Apr 2021\nOwned brand identity and its application across every touchpoint, from wordmark and visual system to sales decks, event collateral, and print production. Built reusable templates and brand guidelines that let non-designers produce on-brand materials independently.",
    },
    {
      id: "capabilities",
      label: "03 Capabilities",
      headline: "Product-first, AI-native.",
      body: "AI product design · 0→1 products · Design systems · Enterprise UX · Prototyping in code · Brand & web · Working with AI tooling as a daily collaborator.",
    },
    {
      id: "contact",
      label: "04 Contact",
      headline: "Say hi.",
      body: "dhe052@hotmail.com, or find me on LinkedIn. Based in the SF Bay Area, working with teams building serious AI tools.",
    },
  ],
};
