import PORTRAIT_ASCII from "./portrait.txt?raw";

export const SITE = {
  name: "Dan He",
  role: "Founding Designer",
  company: "Virtue AI",
  location: "San Francisco",
  status: "Open to work",
  email: "dhe052@hotmail.com",
  linkedin: "#",
  heroTitleA: "I design AI products",
  heroTitleB: "and ship them to production.",
  heroBlurb: "Founding designer at Virtue AI. Brand, product, systems, web.",
  artSignature: "Kernel — generative study",
  artHintCmd: "press [ tune ]",
  artHintSub: "see the system",
};

export const NOT_FOUND = {
  code: "404",
  line: "This path doesn't exist — the art doesn't mind.",
  cta: "[ back to index ]",
};

export const KALEIDO = {
  width: 48,
  height: 20,
  ramp: " .:-=+*o#%@",
};

export const ART = {
  defaults: {
    variant: "orbit",
    symmetry: 6,
    speed: 2,
    scale: 13,
    density: 10,
    palette: "custom",
    customColor: "#C8432A",
    customMode: "multi",
    seed: 0.37,
  },
  variants: [
    { id: "fold", label: "K-Fold" },
    { id: "wave", label: "Wave" },
    { id: "orbit", label: "Orbit" },
    { id: "grid", label: "Moiré" },
  ],
  palettes: [
    { id: "signal", label: "Signal", accent: "#C8432A", colors: { base: "#4a4643", mid: "#8a817a", high: "#C8432A", peak: "#e86a4f" } },
    { id: "ink", label: "Mono Ink", accent: "#F7F5F0", colors: { base: "#3c3934", mid: "#6e6a63", high: "#b5aea4", peak: "#F7F5F0" } },
    { id: "ember", label: "Ember", accent: "#ff6a3c", colors: { base: "#4a2018", mid: "#8a3524", high: "#C8432A", peak: "#ff8a5f" } },
    { id: "terminal", label: "Terminal", accent: "#4fae5f", colors: { base: "#1d3a24", mid: "#2f6b3d", high: "#4fae5f", peak: "#a8ff7a" } },
    { id: "glacier", label: "Glacier", accent: "#5ba3d0", colors: { base: "#22303c", mid: "#3d5a70", high: "#5ba3d0", peak: "#bfe6ff" } },
    { id: "spectrum", label: "Spectrum", accent: "#7a5fff", spectrum: true },
  ],
};

export const WORKS = [
  {
    id: "policyguard",
    motif: "rings",
    num: "01",
    title: "PolicyGuard",
    type: "Product",
    tagline: "The guardrail, rebuilt for the people who own the policy",
    sub: "Virtue's Guard shipped as an API, and every serious deployment still ran through our engineers. I reframed it into a product a policy owner at a bank or hospital composes, tests, and ships on their own.",
    tags: ["0→1", "AI safety", "Enterprise"],
    result: "Guard went from an API our engineers hand-held to a product policy owners run end to end. It is now the product Virtue leads with.",
    gate: {
      label: "Locked",
      headline: "The rest of this case opens by name.",
      body: "The remaining sections cover work that is still confidential. Enter your first name if we've been in touch, the name of whoever sent you here, or the phrase you were given.",
      noteLead: "None of those? Email",
      noteEmail: "dhe052@hotmail.com",
      noteTail: "and I'll open it for you.",
      placeholder: "Name or phrase",
      cta: "Unlock",
      checking: "Checking",
      denied: "I don't recognize that one yet. Email me and I'll let you in.",
      error: "Unlock is unavailable right now. Email dhe052@hotmail.com.",
    },
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "Guard worked as an API. Every deployment still ran through us.",
        body: "When I joined, Virtue was a handful of people, one product owner per product, two products: Guard and red teaming. Guard shipped as an API you tested against, and it quietly became our most profitable line. Any engineer could call it. But composing real enforcement, choosing what to enforce, tuning it, proving it worked, still leaned on our engineers. The capability existed. The product did not. A profitable line proves the need is real, not that anyone has built the right thing around it, and what I built started at zero: the object model, the workflow, and every surface a policy owner touches.",
      },
    ],
  },
  {
    id: "virtuered",
    confidential: true,
    motif: "clash",
    num: "02",
    title: "VirtueRed",
    type: "Product",
    tagline: "The AI red-teaming platform, refactored",
    sub: "Rebuilding an engineer-built adversarial testing tool into an interface security researchers can move fast in.",
    tags: ["Refactor", "AI safety", "Systems"],
    result: "[Dan fills: one-line win]",
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "An engineer-built tool with no design system.",
        body: "[Dan fills: what the tool was, who used it, and what state it was in when you picked it up.]",
        fig: "drop screenshot — the before state",
      },
      {
        id: "gap",
        label: "02 The Gap",
        headline: "[Dan fills: what you saw]",
        body: "[Dan fills: what prompted the refactor — where researchers were losing time or trust.]",
      },
      {
        id: "fix",
        label: "03 The Fix",
        headline: "[Dan fills: the key decision]",
        body: "[Dan fills: what you redesigned — IA, interaction patterns, visual system — and the one call you'd defend.]",
        fig: "drop screenshot — the after state",
      },
      {
        id: "shipped",
        label: "04 What Shipped",
        headline: "[Dan fills]",
        body: "[Dan fills: what went to production and the scope you owned.]",
      },
      {
        id: "outcome",
        label: "05 Outcome",
        headline: "[Dan fills]",
        body: "[Dan fills: impact and what changed.]",
      },
    ],
  },
  {
    id: "design-system",
    motif: "lattice",
    num: "03",
    title: "Design System",
    type: "System",
    tagline: "One language across every product",
    sub: "The shared language behind Virtue's products: tokens, components, and rules, built on a shadcn foundation and grown inside real product work.",
    tags: ["Systems", "Tokens", "Components"],
    result: "Two AI products ship from one set of parts, and the third will inherit them on day one. Treated as a product, not a project, grown through use.",
    gate: {
      label: "Locked",
      headline: "The rest of this case opens by name.",
      body: "The remaining sections cover work that is still confidential. Enter your first name if we've been in touch, the name of whoever sent you here, or the phrase you were given.",
      noteLead: "None of those? Email",
      noteEmail: "dhe052@hotmail.com",
      noteTail: "and I'll open it for you.",
      placeholder: "Name or phrase",
      cta: "Unlock",
      checking: "Checking",
      denied: "I don't recognize that one yet. Email me and I'll let you in.",
      error: "Unlock is unavailable right now. Email dhe052@hotmail.com.",
    },
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "No system, no front-end team, no shared language.",
        body: "When I joined as founding designer, there was no design system and no dedicated front-end engineers. Every surface had been built fast, under deadline, by whoever was closest to it. Put the screens side by side and the story told itself: one company, several visual languages. Nobody's fault. That is what shipping quickly without shared parts looks like.",
      },
    ],
  },
  {
    id: "ai-workflow",
    motif: "mark",
    num: "04",
    title: "AI Workflow",
    type: "Process",
    tagline: "Designing the workflow around AI, not just designing with it",
    sub: "I designed and shipped The Index directly in code, directing AI agents under rules they must obey: intent, facts, and final quality stayed mine. Figma came last, generated from what shipped.",
    tags: ["AI-native", "Workflow", "Solo"],
    result: "The Index is live, designed entirely in production. The method is the deliverable: with agents, design becomes writing constraints that survive execution.",
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "The site you are reading was never mocked up.",
        body: "This portfolio had to prove a claim no static image can: that I work in the codebase and ship. So the build became the case. It started the ordinary way, with references: [Dropbox's brand-guidelines grid](https://brand.dropbox.com), the reading pages of [Raw Materials](https://www.therawmaterials.com), a generative ASCII hero. What never happened is what usually comes next. No artboard, no wireframe. The first time I saw the design, it was running in a browser.",
      },
      {
        id: "decision",
        label: "02 Decision",
        headline: "The source of truth moved into production.",
        body: "I rejected two obvious paths. A template would ship fast and prove nothing. Figma-first would mean designing everything twice, with loss in every translation, for an experience that lives in responsive behavior, generative visuals, and interaction. So the repository became the source of truth and the browser the canvas.\n\nThe trade-off was immediate: iteration got faster, articulation got more expensive. Vague direction produced generic output. Missing facts invited invention. The design skill moved from drawing screens to writing constraints that survive execution.",
      },
      {
        id: "material",
        label: "03 The Material",
        headline: "Vibe coding has no memory and no taste.",
        body: "Raw agent output fails in three predictable ways, and all three are properties of the material. It forgets: every session starts blank, and decisions evaporate. It inflates: one of the first fixes in this repo's history deletes a grand claim an agent wrote about me. It defaults to the average: rounded corners, soft shadows, template typography. None of this argues against the material. It is the brief.",
        imgs: [
          { src: "/work/aiw-diff.png", cap: "The fix on record: an agent's claim about me, deleted" },
        ],
      },
      {
        id: "system",
        label: "04 The System",
        headline: "Every failure mode became a rule.",
        rules: [
          {
            term: "Persist intent",
            text: "The rules live in the repo, not in the chat: palette, sharp corners, bracket tags, even punctuation. Every session starts already knowing them.",
          },
          {
            term: "Protect facts",
            text: "Content is separated from component logic, and anything unverified stays an explicit placeholder. Agents never speak for me.",
          },
          {
            term: "Contain changes",
            text: "Copy lives in one config file and components hold only logic, so an agent editing words cannot break layout.",
          },
          {
            term: "Require evidence",
            text: "No visual change is accepted from a summary. The agent renders the real site at desktop and mobile widths, and I review pixels before anything merges.",
          },
          {
            term: "Decide fast",
            text: "Agents bring options with previews, not open questions. The record of refusals is where the taste lives.",
          },
        ],
        body: "One rule was forced on me. My principle was to let agents run fast, and copy kept breaking it: agents drift grand, and I kept catching claims I would never make. So precision became law, write only what a screenshot can prove, and every user-facing diff still passes through my reading. That cost is permanent. I pay it on purpose.",
        imgs: [
          { src: "/work/aiw-rules.png", cap: "CLAUDE.md: the rules every session reads before touching anything" },
          { src: "/work/aiw-verify-desktop.png", cap: "Agent-rendered verification, 1440px" },
          { src: "/work/aiw-verify-mobile.png", cap: "The same check at 390px, before merge" },
        ],
      },
      {
        id: "outcome",
        label: "05 Outcome",
        headline: "The site shipped. Then the design file, generated from it.",
        body: "The site is live: a modular grid over a generative ASCII engine with its own control deck, case pages built for reading, one set of tokens underneath.\n\nFigma arrived last, pointed the other way. Agents pushed the CSS tokens into Figma as variables through MCP, each carrying its code name, var(--ink), var(--red), as dev-mode syntax. Only a named, complete system survives that translation, so the export doubled as an audit. Figma now documents the system for collaboration. Production stays the source of truth.",
        imgs: [
          { src: "/work/aiw-figma-variables.png", cap: "Foundations in Figma: every token carries its var() name" },
        ],
      },
      {
        id: "contribution",
        label: "06 Contribution",
        headline: "What was mine: the taste, the rules, the no.",
        body: "Agents typed most of the code and built the verification tooling. Mine was what cannot be delegated: the concept, the constraints, every acceptance and every refusal. When execution gets cheap, what stays scarce is knowing what to want and writing it so a machine can follow.\n\nThe principle travels: match the source of truth to the nature of the product. This experience lives in code, so it was designed there. Where exploration or collaboration leads, Figma still earns its place. The same loop, rules and review instead of handoff, runs in my day job. The design system is the deeper story.",
        link: { to: "design-system", label: "Open the design system" },
      },
    ],
  },
  {
    id: "website",
    hidden: true,
    confidential: true,
    motif: "flow",
    num: "05",
    title: "Website",
    type: "Web",
    tagline: "virtueai.com — story, system, ship",
    sub: "The marketing site: explaining hard AI-safety products clearly, designed and shipped hands-on.",
    tags: ["Web", "Marketing", "Copy"],
    result: "[Dan fills: one-line win]",
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "Complex products, one page to earn trust.",
        body: "[Dan fills: what the site needed to do — for buyers, researchers, candidates.]",
      },
      {
        id: "gap",
        label: "02 The Gap",
        headline: "[Dan fills: what wasn't landing]",
        body: "[Dan fills: where the old site lost people — story, IA, clarity.]",
      },
      {
        id: "fix",
        label: "03 The Fix",
        headline: "[Dan fills: IA + narrative + build]",
        body: "[Dan fills: how you restructured the story, wrote the copy, and worked in the codebase to ship it.]",
        fig: "drop screenshot — homepage",
      },
      {
        id: "shipped",
        label: "04 What Shipped",
        headline: "[Dan fills]",
        body: "[Dan fills: pages, launches, product pages shipped.]",
        fig: "drop screenshot — product page",
      },
      {
        id: "outcome",
        label: "05 Outcome",
        headline: "[Dan fills]",
        body: "[Dan fills: traffic, conversion, feedback.]",
      },
    ],
  },
];

export const ABOUT = {
  id: "about",
  num: "06",
  title: "Dan He",
  type: "Profile",
  tagline: "Founding designer, generalist by necessity",
  sub: "San Francisco Bay Area. Currently the founding designer at Virtue AI.",
  tags: ["She/her", "SF Bay Area"],
  photo: "/portrait.jpg",
  portraitAscii: PORTRAIT_ASCII,
  result: null,
  sections: [
    {
      id: "bio",
      label: "01 Bio",
      headline: "One designer, every surface.",
      body: "Founding designer at Virtue AI, an AI security company. The role spans product design across PolicyGuard and VirtueRed, plus the design system, brand, and website. Not a strong coder, but close enough to the code to work in it: shipping styling, copy, and interaction details alongside engineers, using AI to close the gap between design intent and what actually ships.",
    },
    {
      id: "experience",
      label: "02 Experience",
      headline: "Founding designer, by way of brand and product.",
      body: "Founding Designer · Virtue AI\nApr 2025 – Present\nFounding and sole designer at an AI security company, owning product, brand, and web for tools used daily by AI engineers and security teams. Led UX for guardrail, red teaming, and policy configuration, translating complex technical workflows into clear interaction models. Designed PolicyGuard 0→1 from research to launch, refactored the Red Teaming product with engineering, built the company's first design system and brand from scratch, and shipped design directly in the front-end codebase alongside engineers.\n\nDesign Lead · YLEM LLC\nFeb 2024 – Apr 2025\nLed visual and product design across digital experiences and brand execution. Collaborated with clients to define design direction and deliver cohesive user-facing experiences.\n\nUX/UI Design Intern · Mindray\nNov 2022 – Jan 2023\nDesigned ultrasound workstation UX for region-of-interest (ROI) editing and image reordering workflows used in cardiac measurement.\n\nBrand Designer · Zhide Health Consulting\nApr 2019 – Apr 2021\nOwned brand identity and its application across every touchpoint, from wordmark and visual system to sales decks, event collateral, and print production. Built reusable templates and brand guidelines that let non-designers produce on-brand materials independently.",
    },
    {
      id: "capabilities",
      label: "03 Capabilities",
      headline: "Product-first, AI-native.",
      body: "AI product design · 0→1 products · Design systems · Enterprise UX · Prototyping in code · Brand & web · Working with AI tooling as a daily collaborator.",
    },
    {
      id: "offscreen",
      label: "04 Off the clock",
      headline: "Classical music, tennis, badminton.",
      body: "Three things that reward precision and repetition. The overlap with the work is hard to miss.",
    },
    {
      id: "contact",
      label: "05 Contact",
      headline: "Say hi.",
      body: "dhe052@hotmail.com, or find me on LinkedIn. Based in the SF Bay Area, working with teams building serious AI tools.",
    },
  ],
};
