import PORTRAIT_ASCII from "./portrait.txt?raw";

export const SITE = {
  name: "Dan He",
  role: "Founding Designer",
  company: "Virtue AI",
  location: "San Francisco",
  status: "Open to work",
  email: "dhe052@hotmail.com",
  linkedin: "#",
  heroTitleA: "I design AI products",
  heroTitleB: "and ship them to production.",
  heroBlurb: "Founding designer at Virtue AI. Brand, product, systems, web.",
  artSignature: "Kernel — generative study",
  artHintCmd: "press [ tune ]",
  artHintSub: "see the system",
};

export const NOT_FOUND = {
  code: "404",
  line: "This path doesn't exist — the art doesn't mind.",
  cta: "[ back to index ]",
};

export const KALEIDO = {
  width: 48,
  height: 20,
  ramp: " .:-=+*o#%@",
};

export const ART = {
  defaults: {
    variant: "orbit",
    symmetry: 6,
    speed: 2,
    scale: 13,
    density: 10,
    palette: "custom",
    customColor: "#C8432A",
    customMode: "multi",
    seed: 0.37,
  },
  variants: [
    { id: "fold", label: "K-Fold" },
    { id: "wave", label: "Wave" },
    { id: "orbit", label: "Orbit" },
    { id: "grid", label: "Moiré" },
  ],
  palettes: [
    { id: "signal", label: "Signal", accent: "#C8432A", colors: { base: "#4a4643", mid: "#8a817a", high: "#C8432A", peak: "#e86a4f" } },
    { id: "ink", label: "Mono Ink", accent: "#F7F5F0", colors: { base: "#3c3934", mid: "#6e6a63", high: "#b5aea4", peak: "#F7F5F0" } },
    { id: "ember", label: "Ember", accent: "#ff6a3c", colors: { base: "#4a2018", mid: "#8a3524", high: "#C8432A", peak: "#ff8a5f" } },
    { id: "terminal", label: "Terminal", accent: "#4fae5f", colors: { base: "#1d3a24", mid: "#2f6b3d", high: "#4fae5f", peak: "#a8ff7a" } },
    { id: "glacier", label: "Glacier", accent: "#5ba3d0", colors: { base: "#22303c", mid: "#3d5a70", high: "#5ba3d0", peak: "#bfe6ff" } },
    { id: "spectrum", label: "Spectrum", accent: "#7a5fff", spectrum: true },
  ],
};

export const WORKS = [
  {
    id: "policyguard",
    motif: "rings",
    num: "01",
    title: "PolicyGuard",
    type: "Product",
    tagline: "The guardrail, rebuilt for the people who own the policy",
    sub: "Virtue's Guard shipped as an API, and every serious deployment still ran through our engineers. I reframed it into a product a policy owner at a bank or hospital composes, tests, and ships on their own.",
    tags: ["0→1", "AI safety", "Enterprise"],
    result: "Guard went from an API our engineers hand-held to a product policy owners run end to end. It is now the product Virtue leads with.",
    gate: {
      label: "Locked",
      headline: "The rest of this case opens by name.",
      body: "The remaining sections cover work that is still confidential. If we've been in touch, enter your first name to open them.",
      noteLead: "Haven't reached out yet? Email",
      noteEmail: "dhe052@hotmail.com",
      noteTail: "and I'll open it for you.",
      placeholder: "Your first name",
      cta: "Unlock",
      checking: "Checking",
      denied: "I don't have that name yet. Email me and I'll add it.",
      error: "Unlock is unavailable right now. Email dhe052@hotmail.com.",
    },
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "Guard worked as an API. Every deployment still ran through us.",
        body: "When I joined, Virtue was a handful of people, one product owner per product, two products: Guard and red teaming. Guard shipped as an API you tested against, and it quietly became our most profitable line. Any engineer could call it. But composing real enforcement, choosing what to enforce, tuning it, proving it worked, still leaned on our engineers. The capability existed. The product did not. A profitable line proves the need is real, not that anyone has built the right thing around it, and what I built started at zero: the object model, the workflow, and every surface a policy owner touches.",
      },
    ],
  },
  {
    id: "virtuered",
    confidential: true,
    motif: "clash",
    num: "02",
    title: "VirtueRed",
    type: "Product",
    tagline: "The AI red-teaming platform, refactored",
    sub: "Rebuilding an engineer-built adversarial testing tool into an interface security researchers can move fast in.",
    tags: ["Refactor", "AI safety", "Systems"],
    result: "[Dan fills: one-line win]",
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "An engineer-built tool with no design system.",
        body: "[Dan fills: what the tool was, who used it, and what state it was in when you picked it up.]",
        fig: "drop screenshot — the before state",
      },
      {
        id: "gap",
        label: "02 The Gap",
        headline: "[Dan fills: what you saw]",
        body: "[Dan fills: what prompted the refactor — where researchers were losing time or trust.]",
      },
      {
        id: "fix",
        label: "03 The Fix",
        headline: "[Dan fills: the key decision]",
        body: "[Dan fills: what you redesigned — IA, interaction patterns, visual system — and the one call you'd defend.]",
        fig: "drop screenshot — the after state",
      },
      {
        id: "shipped",
        label: "04 What Shipped",
        headline: "[Dan fills]",
        body: "[Dan fills: what went to production and the scope you owned.]",
      },
      {
        id: "outcome",
        label: "05 Outcome",
        headline: "[Dan fills]",
        body: "[Dan fills: impact and what changed.]",
      },
    ],
  },
  {
    id: "design-system",
    confidential: true,
    motif: "lattice",
    num: "03",
    title: "Design System",
    type: "System",
    tagline: "One language across every product",
    sub: "Tokens, components, and rules that let one designer keep two AI products — and everything around them — coherent.",
    tags: ["Systems", "Tokens", "Components"],
    result: "[Dan fills: one-line win — e.g. Two products, one system, zero drift]",
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "Two products, one designer, no shared parts.",
        body: "[Dan fills: the state of the UI across PolicyGuard and VirtueRed before the system existed.]",
      },
      {
        id: "gap",
        label: "02 The Gap",
        headline: "Every screen was drifting from the last.",
        body: "[Dan fills: where inconsistency was costing speed and trust — eng rebuilding variants, mismatched patterns.]",
      },
      {
        id: "fix",
        label: "03 The Fix",
        headline: "Tokens first, components second, rules third.",
        body: "[Dan fills: how you structured the system — color/type/spacing tokens, core components, usage rules — and how AI tooling helped you ship it solo.]",
        fig: "drop screenshot — token + component sheet",
      },
      {
        id: "shipped",
        label: "04 What Shipped",
        headline: "[Dan fills]",
        body: "[Dan fills: coverage — which products and surfaces run on the system.]",
        fig: "drop screenshot — system in production",
      },
      {
        id: "outcome",
        label: "05 Outcome",
        headline: "[Dan fills]",
        body: "[Dan fills: build speed, consistency, eng adoption.]",
      },
    ],
  },
  {
    id: "ai-workflow",
    motif: "mark",
    num: "04",
    title: "AI Workflow",
    type: "Process",
    tagline: "Zero Figma. This site, designed in the medium by directing agents",
    sub: "No artboards, no wireframes, no handoff. I designed The Index directly in code by directing AI agents, with taste and facts governed by rules the agents must obey. Figma appeared only at the end, generated from the code.",
    tags: ["0 Figma", "AI-native", "Solo"],
    result: "A designed site with no design file. The workflow is the deliverable: AI treated as a material, its failure modes understood and designed around.",
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "The site you are reading was never mocked up.",
        body: "This portfolio had to prove a claim no static image can: that I work in the codebase and ship. So the build became the case. It started the ordinary way, with inspiration: [Dropbox's brand-guidelines grid](https://brand.dropbox.com), the reading pages of [Raw Materials](https://www.therawmaterials.com), a generative ASCII hero. What never happened is what usually comes next. No artboard, no wireframe, no mockup. Those references went straight to the agents, and the first time I saw the design, it was already real, in a browser.",
      },
      {
        id: "focus",
        label: "02 Focus",
        headline: "The browser is the canvas. Language is the design tool.",
        body: "Two obvious paths got rejected. A template would ship fast and prove nothing. Figma-first would mean designing everything twice, once in vectors and once in code, with loss in every translation. The bet: if I can articulate intent precisely enough, references, rules, and refusals in plain language, iteration happens at the speed of conversation, in the final medium. The design skill moves from drawing to directing.",
      },
      {
        id: "problem",
        label: "03 Problem & Opportunity",
        headline: "Vibe coding has no memory and no taste.",
        body: "Raw vibe coding fails in three predictable ways, and all three are properties of the material. Models forget: every session starts blank, and decisions evaporate. Models inflate: one of the first fixes in this repo's history is deleting a grand claim an agent wrote about me. And models default to the average: rounded corners, soft shadows, template typography. None of these are reasons to avoid the material. They are the brief. Each failure mode can be designed around, and that design is the work.",
        imgs: [
          { src: "/work/aiw-diff.png", cap: "The fix on record: an agent's claim about me, deleted" },
        ],
      },
      {
        id: "build",
        label: "04 The Build",
        headline: "Understand the material, then build the loop around it.",
        body: "Every property of the model got a mechanism. Memory: taste lives in the repo, not in my head or the chat. A rules file locks the palette, the sharp corners, the bracket tags, even the punctuation, so a fresh session reads it and designs like me. Facts: agents never speak for me. Unwritten content stays as explicit placeholders until I fill it, a hard rule against invented biography. Blast radius: all content lives in one config file and components hold only logic, so an agent editing copy cannot break layout. Verification: no visual change ships on the agent's word. It renders the real site in a real browser, desktop and mobile, and shows me the pixels before anything merges. Model choice: different tasks get different models, a creative one for voice, a heavier one for engineering. Decisions: agents present options with previews, not open questions. I pick, reject, or redirect in seconds, and the record of refusals is where the taste lives.\n\nThe tension ran through all of it. My principle was to let agents run fast. What kept breaking it was copy: agents drifted grand, and I kept catching claims I would never make. So precision became a rule, only write what a screenshot can prove, and every user-facing diff still passes through my reading. That cost is permanent, and I pay it on purpose.",
        imgs: [
          { src: "/work/aiw-rules.png", cap: "CLAUDE.md: the rules every session reads before touching anything" },
          { src: "/work/aiw-verify-desktop.png", cap: "Agent-rendered verification, 1440px" },
          { src: "/work/aiw-verify-mobile.png", cap: "The same check at 390px, before merge" },
        ],
      },
      {
        id: "outcome",
        label: "05 Outcome",
        headline: "A designed site, no design file. Then the design file, generated from code.",
        body: "The Index is live: a modular grid over a generative ASCII engine with its own control deck, five works, case pages built for reading. Iteration runs at conversation speed; a hero rewrite goes from sentence to production in minutes. And Figma did appear, at the end, pointed the other way on purpose. Through MCP, agents pushed the CSS tokens into Figma as variables, each carrying its code name, var(--ink), var(--red), as its dev-mode syntax. The direction is the point. When Figma sits upstream, the library and production drift apart and nobody can say which one is right. Generated from what ships, the file cannot drift: it is a projection of production, regenerated whenever it falls behind, and the next designer composes with parts that already exist. It also proved the tokens were real, since only a named, complete system survives that translation. Figma documents the system. It never designed it.",
        imgs: [
          { src: "/work/aiw-figma-variables.png", cap: "Foundations in Figma: every token carries its var() name" },
        ],
      },
      {
        id: "contribution",
        label: "06 Contribution",
        headline: "What was mine: the taste, the rules, the no.",
        body: "The agents typed most of the code and built the verification tooling. Mine was everything that cannot be delegated: the concept, the rules layer that makes agents design like me, the architecture that contains them, the model choices, and every acceptance and refusal along the way. When execution gets cheap, what stays scarce is knowing what to want, writing it as constraints a machine can follow, and saying no to what is wrong.",
      },
      {
        id: "next",
        label: "07 Next",
        headline: "This is how I work, not how I hobby.",
        body: "The same loop runs in my day job: prototyping in code alongside engineers, rules and review instead of handoff. The design system this site runs on, and the one it exported to Figma, is the deeper story.",
        link: { to: "design-system", label: "Open the design system" },
      },
    ],
  },
  {
    id: "website",
    hidden: true,
    confidential: true,
    motif: "flow",
    num: "05",
    title: "Website",
    type: "Web",
    tagline: "virtueai.com — story, system, ship",
    sub: "The marketing site: explaining hard AI-safety products clearly, designed and shipped hands-on.",
    tags: ["Web", "Marketing", "Copy"],
    result: "[Dan fills: one-line win]",
    sections: [
      {
        id: "context",
        label: "01 Context",
        headline: "Complex products, one page to earn trust.",
        body: "[Dan fills: what the site needed to do — for buyers, researchers, candidates.]",
      },
      {
        id: "gap",
        label: "02 The Gap",
        headline: "[Dan fills: what wasn't landing]",
        body: "[Dan fills: where the old site lost people — story, IA, clarity.]",
      },
      {
        id: "fix",
        label: "03 The Fix",
        headline: "[Dan fills: IA + narrative + build]",
        body: "[Dan fills: how you restructured the story, wrote the copy, and worked in the codebase to ship it.]",
        fig: "drop screenshot — homepage",
      },
      {
        id: "shipped",
        label: "04 What Shipped",
        headline: "[Dan fills]",
        body: "[Dan fills: pages, launches, product pages shipped.]",
        fig: "drop screenshot — product page",
      },
      {
        id: "outcome",
        label: "05 Outcome",
        headline: "[Dan fills]",
        body: "[Dan fills: traffic, conversion, feedback.]",
      },
    ],
  },
];

export const ABOUT = {
  id: "about",
  num: "06",
  title: "Dan He",
  type: "Profile",
  tagline: "Founding designer, generalist by necessity",
  sub: "San Francisco Bay Area. Currently the founding designer at Virtue AI.",
  tags: ["She/her", "SF Bay Area"],
  photo: "/portrait.jpg",
  portraitAscii: PORTRAIT_ASCII,
  result: null,
  sections: [
    {
      id: "bio",
      label: "01 Bio",
      headline: "One designer, every surface.",
      body: "Founding designer at Virtue AI, an AI security company. The role spans product design across PolicyGuard and VirtueRed, plus the design system, brand, and website. Not a strong coder, but close enough to the code to work in it: shipping styling, copy, and interaction details alongside engineers, using AI to close the gap between design intent and what actually ships.",
    },
    {
      id: "experience",
      label: "02 Experience",
      headline: "Founding designer, by way of brand and product.",
      body: "Founding Designer · Virtue AI\nApr 2025 – Present\nFounding and sole designer at an AI security company, owning product, brand, and web for tools used daily by AI engineers and security teams. Led UX for guardrail, red teaming, and policy configuration, translating complex technical workflows into clear interaction models. Designed PolicyGuard 0→1 from research to launch, refactored the Red Teaming product with engineering, built the company's first design system and brand from scratch, and shipped design directly in the front-end codebase alongside engineers.\n\nDesign Lead · YLEM LLC\nFeb 2024 – Apr 2025\nLed visual and product design across digital experiences and brand execution. Collaborated with clients to define design direction and deliver cohesive user-facing experiences.\n\nUX/UI Design Intern · Mindray\nNov 2022 – Jan 2023\nDesigned ultrasound workstation UX for region-of-interest (ROI) editing and image reordering workflows used in cardiac measurement.\n\nBrand Designer · Zhide Health Consulting\nApr 2019 – Apr 2021\nOwned brand identity and its application across every touchpoint, from wordmark and visual system to sales decks, event collateral, and print production. Built reusable templates and brand guidelines that let non-designers produce on-brand materials independently.",
    },
    {
      id: "capabilities",
      label: "03 Capabilities",
      headline: "Product-first, AI-native.",
      body: "AI product design · 0→1 products · Design systems · Enterprise UX · Prototyping in code · Brand & web · Working with AI tooling as a daily collaborator.",
    },
    {
      id: "offscreen",
      label: "04 Off the clock",
      headline: "Classical music, tennis, badminton.",
      body: "Three things that reward precision and repetition. The overlap with the work is hard to miss.",
    },
    {
      id: "contact",
      label: "05 Contact",
      headline: "Say hi.",
      body: "dhe052@hotmail.com, or find me on LinkedIn. Based in the SF Bay Area, working with teams building serious AI tools.",
    },
  ],
};
